package Types;

public enum OperatorTypes implements TokenType
{
    OPERATOR_ASSIGNMENT,
    OPERATOR_GREATER,
    OPERATOR_LOWER,
    OPERATOR_DECREMENT,
    OPERATOR_INCREMENT,
    OPERATOR_SUM,
    OPERATOR_MINUS,
    OPERATOR_DIVISION,
    OPERATOR_MULTIPLICATION,
    OPERATOR_EQUAL,
    OPERATOR_LOWEST_OR_EQUAL,
    OPERATOR_GREATER_OR_EQUAL,
    OPERATOR_NOT_EQUAL,
    OPERATOR_MODULE,
    OPERATOR_INT_DIVISION,
    OPERATOR_AND,
    OPERATOR_OR,
    OPERATOR_TRUE
}
